# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dda91a938d9c0b2d4b5efcc923ae1bf3d3405424c22a8c572aae37294eaef7ecd04d759cd2a544c9cb2934e38d148b356d644e5b4f8f5d934a98ff6ca269749b

test:
  secret_key_base: 16a4f0396a1345ccdba7719ac990e27b4d390b099fddda2a80a54565b46933b2f405608ba2e961b594763f3514a69594e46aa40c6a2b53159ae9e78fd0de65b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
